version: '3.7'
services: 
 server:
  build: .
  volumes:
  - .:/usr/src/app
  - /usr/src/app/node_modules
  ports:
  - 3001:3001
 client:
  build: ../WikiVisa_Client
  volumes:
  - ../WikiVisa_Client:/usr/src/app
  - /usr/src/app/node_modules
  ports:
  - 80:3000
  depends_on: 
  - server